### ISSUE TITLE
QS crashes when opening the context menu of some System Tray Items

### ISSUE THREAD

**Issue by nydragon** [outfoxxed/quickshell#5]
### General crash information

<details> <summary>General information</summary>

```
===== Quickshell Crash =====
Git Revision: 01f2be057e3425064bcc5fa4cf657a534adfd992
Crashed process ID: 52130
Run ID: o5412e4vjs

===== Shell Information =====
Shell ID: e21932e752024fe990ad40799e1fae54
Config Path: /home/ny/Documents/projects/nysh/src/shell.qml

===== Report Integrity =====
Minidump save status: 0
Log save status: 0

===== System Information =====
Qt Version: 6.7.2

/etc/os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240911.4f807e8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"

/etc/lsb-release:
DISTRIB_CODENAME=vicuna
DISTRIB_DESCRIPTION="NixOS 24.11 (Vicuna)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="24.11"
LSB_VERSION="24.11 (Vicuna)"
```

</details>

### What caused the crash

Opening the context menu of a SystemTrayItem, however this does not happen with every tray element:

**Crashes**
- blueman-manager
- protonmail-bridge

**Does not crash**
- kdeconnect
- gammastep
- nextcloud
- keepassxc
- steam

This behaviour stays consistent across reboots and whatnot

### Minidump

[minidump.dmp](https://github.com/user-attachments/files/17006516/minidump.dmp)

### Log file

[logs.txt](https://github.com/user-attachments/files/17006519/logs.txt)

It's still the qslog file, GitHub wouldn't allow me to upload it otherwise

### Configuration

https://github.com/Nydragon/nysh

Install one of:
- blueman
- protonmail-bridge

Make sure they are running and execute 

`nix run github:Nydragon/nysh`

### Backtrace

<details><summary>Details</summary>
<p>

```
#0  0x00007f3a9c9e7310 in QWidget::createWinId() () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Widgets.so.6
No symbol table info available.
#1  0x000055753632b4e2 in qs::menu::platform::PlatformMenuEntry::display(PopupAnchor*) ()
No symbol table info available.
#2  0x0000557536330235 in qs::menu::QsMenuAnchor::onMenuChanged() ()
No symbol table info available.
#3  0x00007f3a9b5eb170 in void doActivate<false>(QObject*, int, void**) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#4  0x00007f3a9b5eb170 in void doActivate<false>(QObject*, int, void**) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#5  0x00005575363e5419 in qs::dbus::dbusmenu::DBusMenu::updateLayoutRecursive(DBusMenuLayout const&, qs::dbus::dbusmenu::DBusMenuItem*, int) ()
No symbol table info available.
#6  0x00005575363e6e6b in QtPrivate::QCallableObject<qs::dbus::dbusmenu::DBusMenu::updateLayout(int, int)::$_0, QtPrivate::List<QDBusPendingCallWatcher*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
No symbol table info available.
#7  0x00007f3a9b5eb170 in void doActivate<false>(QObject*, int, void**) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#8  0x00007f3a9c5c69cf in QDBusPendingCallWatcher::finished(QDBusPendingCallWatcher*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6DBus.so.6
No symbol table info available.
#9  0x00007f3a9b5dc8cb in QObject::event(QEvent*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#10 0x00007f3a9c9950f5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Widgets.so.6
No symbol table info available.
#11 0x00007f3a9b585a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#12 0x00007f3a9b5897c9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#13 0x00007f3a9b863c13 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#14 0x00007f3a9ad170a4 in g_main_dispatch () from /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
No symbol table info available.
#15 0x00007f3a9ad1a2c7 in g_main_context_iterate_unlocked.isra () from /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
No symbol table info available.
#16 0x00007f3a9ad1a8ec in g_main_context_iteration () from /nix/store/pjxrn2wn0sn533p48jz5qxgjld84hn3i-glib-2.80.4/lib/libglib-2.0.so.0
No symbol table info available.
#17 0x00007f3a9b86347c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#18 0x00007f3a9b592d33 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
No symbol table info available.
#19 0x00007f3a9b58eb96 in QCoreApplication::exec() () from /nix/store/82n7plcl529pfa8ymv0gpybzx5d9zd6b-qtbase-6.7.2/lib/libQt6Core.so.6
--Type <RET> for more, q to quit, c to continue without paging--c
No symbol table info available.
#20 0x00005575362b24b3 in qs::launch::launch(qs::launch::LaunchArgs const&, char**, QCoreApplication*) ()
No symbol table info available.
#21 0x00005575362ae0fe in qs::launch::launchFromCommand(qs::launch::CommandState&, QCoreApplication*) ()
No symbol table info available.
#22 0x00005575362aa011 in qs::launch::runCommand(int, char**, QCoreApplication*) ()
No symbol table info available.
#23 0x00005575362a682f in qs::launch::main(int, char**) ()
No symbol table info available.
#24 0x00007f3a9ae3314e in __libc_start_call_main () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#25 0x00007f3a9ae33209 in __libc_start_main_impl () from /nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libc.so.6
No symbol table info available.
#26 0x0000557536290245 in _start ()
No symbol table info available.
```

</p>
</details>

**Comment by outfoxxed** [comment]
I've known about this one for a long time and haven't ever been able to reproduce it consistently. Can you reproduce it consistently with the listed programs?

**Comment by nydragon** [comment]
Yes, just tried it 10 times (with a full qs restart) and it crashed on all occasions when opening the blueman menu
